import { Link } from 'react-router-dom';
import Navbar from '../components/Navbar';

const Terms = () => {
  return (
    <div className="min-h-screen bg-black text-white">
      <Navbar />
      <main className="container mx-auto px-6 lg:px-12 pt-32 pb-20 max-w-4xl">
        <h1 className="text-4xl md:text-5xl font-bold mb-8 tracking-tight">Terms &amp; Conditions</h1>
        <p className="text-gray-400 mb-12">Last updated: February 24, 2025</p>

        <div className="space-y-10 text-gray-300 leading-relaxed">
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">1. Acceptance of Terms</h2>
            <p>By accessing and using ReviewDekho ("the Platform"), you agree to be bound by these Terms and Conditions. If you do not agree with any part of these terms, you must not use the Platform.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">2. Description of Service</h2>
            <p>ReviewDekho provides AI-powered trust intelligence and seller verification services for online marketplaces. The Platform uses AMD hardware-accelerated inference to analyze seller data, generate trust scores, and detect potential fraud — all processed locally without transmitting user data to external servers.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">3. User Accounts</h2>
            <p>You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must notify ReviewDekho immediately of any unauthorized use of your account.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">4. Acceptable Use</h2>
            <p>You agree not to misuse the Platform, including but not limited to:</p>
            <ul className="list-disc list-inside mt-2 space-y-1 text-gray-400">
              <li>Attempting to reverse-engineer the AI models or inference pipeline</li>
              <li>Using the Platform to harass, defame, or harm any seller or marketplace</li>
              <li>Submitting false or misleading data to manipulate trust scores</li>
              <li>Accessing the Platform through automated means without authorization</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">5. Intellectual Property</h2>
            <p>All content, features, and functionality of the Platform — including AI models, scoring algorithms, and user interface — are owned by ReviewDekho and are protected by copyright, trademark, and other intellectual property laws.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">6. Disclaimer of Warranties</h2>
            <p>Trust scores and risk assessments are generated by AI models and should be used as informational tools only. ReviewDekho does not guarantee the accuracy of any trust score and shall not be liable for decisions made based on Platform outputs.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">7. Limitation of Liability</h2>
            <p>In no event shall ReviewDekho be liable for any indirect, incidental, special, consequential, or punitive damages arising out of or relating to your use of the Platform.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">8. Modifications</h2>
            <p>ReviewDekho reserves the right to modify these Terms at any time. Continued use of the Platform following any changes constitutes acceptance of the revised Terms.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">9. Contact</h2>
            <p>For questions about these Terms, please contact us at <a href="mailto:legal@reviewdekho.ai" className="text-blue-400 hover:underline">legal@reviewdekho.ai</a>.</p>
          </section>
        </div>

        <div className="mt-16 pt-8 border-t border-white/10">
          <Link to="/" className="text-gray-400 hover:text-white transition-colors text-sm">← Back to Home</Link>
        </div>
      </main>
    </div>
  );
};

export default Terms;
